user  nginx;

events {
    worker_connections   1000;
}
http {
  # Use docker's internal nameserver
  resolver 127.0.0.11 valid=10s ipv6=off;

  upstream carbone-backend{
    # Set dns resolution in volatile memory
    zone carboneservers 64k;
    # Enable dns resolution to get new of disabled instances
    server carbone-ee:4000 resolve;
  }
  
  server {
    listen 4000;
    location / {
      proxy_pass http://carbone-backend;
    }
    client_max_body_size 20M;
  }
}
