user  nginx;

events {
    worker_connections   1000;
}
http {
        server {
              listen 80;
              server_name    *** REPLACE BY HOSTNAME ***;

              return         301 https://$server_name$request_uri; #Redirection
        }

        server {
              listen 443 ssl;
              server_name    *** REPLACE BY HOSTNAME ***;

              ssl_protocols TLSv1.2;

              ssl_certificate /etc/nginx/ssl/cert.pem;
              ssl_certificate_key /etc/nginx/ssl/privkey.pem;
              location / {
                proxy_pass http://carbone:4000;
              }
        }
}
