name: Release Carbone Docker

on:
    workflow_dispatch:
      inputs:
        lo_version:
          type: string
          description: Version number. Tag in libreoffice repository
          required: true
          default: "26.2.1.1"
        oo_version:
          type: string
          description: OnlyOffice version
          required: true
          default: "9.0.4"
        chrome_version:
          type: string
          description: Chrome version
          required: true
          default: "141.0.7390.55"
        carbone_version:
          type: string
          description: Version of Carbone-ee
          required: true
          default: "5.3.0"
        target_platforms:
          type: string
          description: target platforms
          required: true
          default: "linux/amd64,linux/arm64"
        update_latest:
          type: boolean
          description: Update latest tags
          required: true
          default: true

jobs:
  start-external-builder:
    name: Start self-hoster EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0ef9bcd5dfb57b968
          ec2-instance-type: t3.medium
          subnet-id: subnet-027c65f285842519c
          security-group-id: sg-0ffdee926e8fcecc2
          iam-role-name: EC2-SSM # optional, requires additional permissions
          aws-resource-tags: > # optional, requires additional permissions
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "ST", "Value": "Carbone-docker-Builder"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]
          pre-runner-script: |
            apt-get update
            apt-get install -y docker.io unzip curl
            usermod -aG docker ubuntu
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install

  build:
    needs: start-external-builder
    runs-on: ${{ needs.start-external-builder.outputs.label }}
    steps:
    - name: Get dep major version
      id: getMajorVersion
      env:
        LO_FULL_VERSION: ${{ inputs.lo_version }}
        OO_FULL_VERSION: ${{ inputs.oo_version }}
        CHROME_FULL_VERSION: ${{ inputs.chrome_version }}
      run: |
        echo "libreOfficeMajorVersion=${LO_FULL_VERSION%.*.*}" >> $GITHUB_OUTPUT
        echo "onlyOfficeMajorVersion=${OO_FULL_VERSION%.*}" >> $GITHUB_OUTPUT
        echo "chromeMajorVersion=${CHROME_FULL_VERSION%.*.*.*}" >> $GITHUB_OUTPUT

    - name: Expand root volume
      run: |
        TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
        INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/instance-id)
        VOLUME_ID=$(aws ec2 describe-volumes --filters Name=attachment.instance-id,Values=$INSTANCE_ID | jq -r .Volumes[0].Attachments[0].VolumeId)
        echo $INSTANCE_ID
        echo $VOLUME_ID
        aws ec2 modify-volume --volume-id $VOLUME_ID --size 32
        sleep 15  # let it update
        growpart /dev/nvme0n1 1
        lsblk
        resize2fs  /dev/nvme0n1p1
        df -hT

    -
      name: Checkout
      uses: actions/checkout@v4

    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.target_platforms }}

    -
      name: Buildx and push slim variant
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.target_platforms }}
        context: ./
        provenance: mode=max
        sbom: true
        build-args: |
          CARBONE_VERSION=${{ inputs.carbone_version }}
        file: ./Dockerfile-slim
        push: true
        tags: |
          ${{ vars.DOCKERHUB_ORG }}/carbone-ee:slim-${{ inputs.carbone_version }}

    -
      name: Buildx and push full variant
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.target_platforms }}
        context: ./
        provenance: mode=max
        sbom: true
        build-args: |
          CARBONE_VERSION=${{ inputs.carbone_version }}
          LO_VERSION=${{ inputs.lo_version }}
          OO_VERSION=${{ inputs.oo_version }}
          CHROME_VERSION=${{ inputs.chrome_version }}
        file: ./Dockerfile
        push: true
        tags: |
          ${{ vars.DOCKERHUB_ORG }}/carbone-ee:full-${{ inputs.carbone_version }}-L${{ steps.getMajorVersion.outputs.libreOfficeMajorVersion }}-O${{ steps.getMajorVersion.outputs.onlyOfficeMajorVersion }}-C${{ steps.getMajorVersion.outputs.chromeMajorVersion }}
          ${{ inputs.update_latest == true && format('{0}/carbone-ee:full-{1}', vars.DOCKERHUB_ORG, inputs.carbone_version) || '' }}
          ${{ inputs.update_latest == true && format('{0}/carbone-ee:full', vars.DOCKERHUB_ORG) || '' }}
          ${{ inputs.update_latest == true && format('{0}/carbone-ee:latest', vars.DOCKERHUB_ORG) || '' }}

    -
      name: Checkout fonts
      uses: actions/checkout@v4
      with:
        repository: carboneio/carbone-fonts
        path: carbone-fonts
        ref: master
        ssh-key: ${{ secrets.PRIVATE_KEY_FONT_REPO }}

    - 
      name: Remove commercial font
      run: rm -r carbone-fonts/custom
    -
      name: Build and push font variant
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./
        provenance: mode=max
        sbom: true
        build-args: |
          CARBONE_VERSION=${{ inputs.carbone_version }}
          LO_VERSION=${{ inputs.lo_version }}
          OO_VERSION=${{ inputs.oo_version }}
          CHROME_VERSION=${{ inputs.chrome_version }}
        file: ./Dockerfile-fonts
        push: true
        tags: |
          ${{ vars.DOCKERHUB_ORG }}/carbone-ee:full-${{ inputs.carbone_version }}-L${{ steps.getMajorVersion.outputs.libreOfficeMajorVersion }}-O${{ steps.getMajorVersion.outputs.onlyOfficeMajorVersion }}-C${{ steps.getMajorVersion.outputs.chromeMajorVersion }}-fonts
          ${{ inputs.update_latest == true && format('{0}/carbone-ee:full-{1}-fonts', vars.DOCKERHUB_ORG, inputs.carbone_version) || '' }}
          ${{ inputs.update_latest == true && format('{0}/carbone-ee:full-fonts', vars.DOCKERHUB_ORG) || '' }}
          ${{ inputs.update_latest == true && format('{0}/carbone-ee:latest-fonts', vars.DOCKERHUB_ORG) || '' }}
  stop-arm-builder:
    name: Stop self-hosted EC2 runner
    needs:
      - start-external-builder # required to get output from the start-runner job
      - build # required to wait when the main job is doen
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-external-builder.outputs.label }}
          ec2-instance-id: ${{ needs.start-external-builder.outputs.ec2-instance-id }}
