name: Release Carbone Docker

on:
    workflow_dispatch:
      inputs:
        lo_version:
          type: string
          description: Version number. Tag in libreoffice repository
          required: true
          default: "25.2.4.3"
        oo_version:
          type: string
          description: OnlyOffice version
          required: true
          default: "9.0.0"
        chrome_version:
          type: string
          description: Chrome version
          required: true
          default: "138.0.7204.50"
        carbone_version:
          type: string
          description: Version of Carbone-ee
          required: true
          default: "5.0.0-beta.13"
        target_platforms:
          type: string
          description: target platforms
          required: true
          default: "linux/amd64,linux/arm64"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get LO major version
      id: getMajorVersion
      env:
        LO_MAJOR_VERSION: ${{ inputs.lo_version }}
      run: echo "libreOfficeMajorVersion=${LO_MAJOR_VERSION%.*.*}" >> $GITHUB_OUTPUT

    -
      name: Checkout
      uses: actions/checkout@v4

    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ inputs.target_platforms }}
      
    -
      name: Buildx and push slim variant
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.target_platforms }}
        context: ./
        provenance: mode=max
        sbom: true
        build-args: |
          CARBONE_VERSION=${{ inputs.carbone_version }}
        file: ./Dockerfile-slim
        push: true
        tags: |
          ${{ vars.DOCKERHUB_ORG }}/carbone-ee:slim-${{ inputs.carbone_version }}

    -
      name: Buildx and push full variant
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.target_platforms }}
        context: ./
        provenance: mode=max
        sbom: true
        build-args: |
          CARBONE_VERSION=${{ inputs.carbone_version }}
          LO_VERSION=${{ inputs.lo_version }}
          OO_VERSION=${{ inputs.oo_version }}
          CHROME_VERSION=${{ inputs.chrome_version }}
        file: ./Dockerfile
        push: true
        tags: |
          ${{ vars.DOCKERHUB_ORG }}/carbone-ee:full-${{ inputs.carbone_version }}-L${{ steps.getMajorVersion.outputs.libreOfficeMajorVersion }}-O9.0-C138
          ${{ vars.DOCKERHUB_ORG }}/carbone-ee:full-${{ inputs.carbone_version }}

    -
      name: Checkout fonts
      uses: actions/checkout@v4
      with:
        repository: carboneio/carbone-fonts
        path: carbone-fonts
        ref: master
        ssh-key: ${{ secrets.PRIVATE_KEY_FONT_REPO }}

    - 
      name: Remove commercial font
      run: rm -r carbone-fonts/custom
    -
      name: Build and push font variant
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./
        provenance: mode=max
        sbom: true
        build-args: |
          CARBONE_VERSION=${{ inputs.carbone_version }}
          LO_VERSION=${{ inputs.lo_version }}
          OO_VERSION=${{ inputs.oo_version }}
          CHROME_VERSION=${{ inputs.chrome_version }}
        file: ./Dockerfile-fonts
        push: true
        tags: |
          ${{ vars.DOCKERHUB_ORG }}/carbone-ee:full-${{ inputs.carbone_version }}-L${{ steps.getMajorVersion.outputs.libreOfficeMajorVersion }}-O9.0-C138-fonts
          ${{ vars.DOCKERHUB_ORG }}/carbone-ee:full-${{ inputs.carbone_version }}-fonts
